blog/urls.py
from django.urls import path
from .views import post_list, post_create, post_detail, post_update, post_delete, like

app_name = "blog"
urlpatterns = [
    path("",post_list, name="list"),
    path("create/",post_create, name="create"),
    path("<str:slug>/",post_detail, name="detail"),
    path("<str:slug>/update/",post_update, name="update"),
    path("<str:slug>/delete/",post_delete, name="delete"),
    path("<str:slug>/like/",like, name="like"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/',include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
    <title>Blog Project</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container" style="padding: 50px 5px 5px 5px;">
        {% if messages %}
        {% for message in messages %}

        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>

        {% endfor %}
        {% endif %}

        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/74c8282b8a.js" crossorigin="anonymous"></script>

</body>

</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% comment %} {% url 'blog:list' %} {% endcomment %}
    <a class="navbar-brand" href="#"><img height="50px"
            src="https://clarusway.com/wp-content/uploads/2022/08/clarusway_925x1182-235x300.png"
            alt="CLARUSWAY_LOGO" />

        Clarusway FS</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
                {% comment %} {% url 'blog:list' %} {% endcomment %}
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">About</a>
            </li>
        </ul>
    </div>

    <div>
        <ul class="navbar-nav navbar-right">

            {% if request.user.is_authenticated %}

            {% if request.user.is_superuser %}

            <li class="nav-item active">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            {% endif %}

            <li class="nav-item active">
                {% comment %} {% url 'logout' %} {% endcomment %}
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
            <li class="nav-item active">
                {% comment %} {% url 'profile' %} {% endcomment %}
                <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item active">
                {% comment %} {% url 'blog:create' %} {% endcomment %}
                <a class="nav-link" href="#">New Post</a>
            </li>
            {% else %}

            <li class="nav-item active">
                {% comment %} {% url 'login' %} {% endcomment %}
                <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>

            <li class="nav-item active">
                {% comment %} {% url 'register' %} {% endcomment %}
                <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>

            {% endif %}

        </ul>
    </div>
</nav>